repos:
- repo: https://github.com/ambv/black
  rev: 18.6b4
  hooks:
  - id: black
    args: [--line-length=120, --safe]
    language_version: python3.7
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.0.1
  hooks:
  - id: seed-isort-config
    args: [--application-directories, src]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/asottile/pyupgrade
  rev: v1.4.0
  hooks:
  - id: pyupgrade
